atlantis-url: "https://localhost:4141"
gh-user: "sarah97"
gh-token: "040ca8ae946299b625515c8eee1454f33f6c32f0"
gh-webhook-secret: "sMK597uW53dU8oKNVF9"
repo-whitelist: "github.com/sarah97/atlantis-test"
allow-repo-config: true